### ISSUE TITLE
[Request] Qt static link build. 

### ISSUE THREAD

**Issue by jgh0721** [Alexpux/Qt-builds#1]
I wan to bulild and link Qt and the other modules statically. but currently, your script support only shared build. 

Thanks for you.

**Comment by Alexpux** [comment]
Do you need Qt4 or Qt5 static link? Or both?

**Comment by jgh0721** [comment]
I needs both Qt4 and Qt5. 

ps. Do you know how to build qt 4 or qt 5 OCI library( Oracle QtSql Module ). I cannot build oci library using mingw. 

Thanks for you.

**Comment by Alexpux** [comment]
I can see this if you need. My builds build plugins only for mysql, postgresql and firebird

**Comment by Alexpux** [comment]
I starting work on static builds of Qt

**Comment by jgh0721** [comment]
Yes, I needs OCI Library for QtSql module using MinGW. 

Thanks for your efforts. 

I have another question. I just have been built Qt 5.0.1 for MinGW using your build scripts. But, console apps are works fine. windows apps doesn't works. below image is error message. 

my system is 
 OS : Windows 7 x64 Ultimate. 
 Dev Tools : your Qt-Build Scripts, VS 2008SP1, VS 2010SP1, VS2012 UP1

![Clipboard](https://f.cloud.github.com/assets/1096534/89954/5c384726-655f-11e2-9c90-548f9bfa3c5e.png)

**Comment by Alexpux** [comment]
Do you launch program from QtCreator? Do you copy dlls from prerequisites folder?

**Comment by jgh0721** [comment]
Yes, I copied my required dlls to prerequistes folders ( ex), qt\bin ) , I got error dialog box when launching assistant.exe, designer.exe, and so on. 

my copied dlls list using dependency walker:

 icudt50.dll
 icuin50.dll
 icuuc50.dll
 libgcc_s_sjlj-1.dll
 libgomp-1.dll
 liblzma-5.dll
 libpcre16-0.dll
 libsqlite3-0.dll
 libssp-0.dll
 libstdc++-6.dll
 libwinpthread-1.dll
 libxml2-2.dll
 libxslt-1.dll

 qminimal.dll
 qminimald.dll

 qwindows.dll
 qwindowsd.dll

**Comment by Alexpux** [comment]
Try to download Dependency Walker from http://www.dependencywalker.com for your Qt build (32 or 64 bit) and open, for example, assistant.exe in dependency walker. If you missing some ddlx it show you.

**Comment by jgh0721** [comment]
hm... yeah, Using dependencywalker, I copied all required dlls to qt\bin folder. but I got above errors. :-(

**Comment by Alexpux** [comment]
What version of Qt you built? Can you post screenshot from Dependency Walker?

**Comment by jgh0721** [comment]
I built Qt version 5.0.1 x32, x64 

Additionaly, I copied libiconv-2.dll to qt\bin folder. but still i got error dialog box;

![Clipboard](https://f.cloud.github.com/assets/1096534/90385/c64b7b28-6574-11e2-9b63-5a0e1475fc3e.png)
![Clipboard_](https://f.cloud.github.com/assets/1096534/90386/c6741d26-6574-11e2-9224-b7643ae6b394.png)
![Clipboard__](https://f.cloud.github.com/assets/1096534/90387/c69acd7c-6574-11e2-83fd-a7d2db5ac1c3.png)
![Clipboard___](https://f.cloud.github.com/assets/1096534/90388/c6b92d62-6574-11e2-9929-f429cdc84da3.png)

Thanks for your efforts. :-)

**Comment by Alexpux** [comment]
Open webkit dll in dependency walker and show me screenshots. Bu do screenshots with middle expanded part not top part

**Comment by jgh0721** [comment]
this is qt5webkit.dll in assistant.exe 
![Clipboard__](https://f.cloud.github.com/assets/1096534/90444/93613ffc-6576-11e2-9c31-78fc18247620.png)

**Comment by Alexpux** [comment]
First, post screenshot with opened second part of window where you have "Error opening file". Second try to launch my build http://sourceforge.net/projects/mingwbuilds/files/external-binary-packages/Qt-Builds/Qt-5.0.1-x32.7z/download.
And do you rename or move folder with Qt after build?

**Comment by jgh0721** [comment]
oh.. yeah. I rename and move initially installed qt folders. First, I restore folder name and there, just works fine. So I got questions. Why couldn't rename or move initially qt folders?

**Comment by Alexpux** [comment]
Qt store installation paths hardwood in libraries. To use Qt from different path you need patch them and hardcode another path. I work on patch program.

**Comment by jgh0721** [comment]
Ok. I got it. Thanks for your answer. :-)

**Comment by Alexpux** [comment]
I add support to build OCI plugin. You need get latest scripts from master branch. If you have any issue about this - write me.

**Comment by jgh0721** [comment]
Oh, Thanks you!!

**Comment by Alexpux** [comment]
If you need to move Qt folder to another location you can create qt.conf file in "bin" subdirectory with next content:

[Paths]
Prefix = c:/QtSDK/Qt4
Translations = translations

Where Prefix is new Qt folder location

**Comment by Alexpux** [comment]
Now you can build static Qt by pass "--static-qt" to build script. But Qt5 has many issues with static build and it builded without ANGLE, ICU, Webkit and SQL drivers.
