### ISSUE TITLE
freetype scenario fails

### ISSUE THREAD

**Issue by ParanoidRabbid** [Alexpux/Qt-builds#11]
This urls:
URL=http://download.savannah.gnu.org/releases/${P}/${SRC_FILE}
URL_DOC=http://download.savannah.gnu.org/releases/${P}/${DOC_FILE}
gives 404 error.

My solution was : 

URL=ftp://mirror.ovh.net/gentoo-distfiles/distfiles/${SRC_FILE}
URL_DOC=ftp://mirror.ovh.net/gentoo-distfiles/distfiles/${DOC_FILE}

**Comment by Alexpux** [comment]
URL is valid. Maybe this is some problems with site

**Comment by ParanoidRabbid** [comment]
My apologise.

The default URL redirects me to : http://mirror.yongbok.net/nongnu//freetype/   wich gives 404

By the way, this work perfectly:
http://download-mirror.savannah.gnu.org/releases/freetype/
