### ISSUE TITLE
Support 5.1 builds

### ISSUE THREAD

**Issue by bratao** [Alexpux/Qt-builds#12]
Hello,
5.1 is coming and a lot of things depends on it now ( like qtquick components). The Git build just fines and would be nice if this was a supported scenario.

**Comment by Alexpux** [comment]
I view it on few days.

**Comment by Alexpux** [comment]
What branch I need to clone?

**Comment by bratao** [comment]
You need the dev branch.
I got by doing:
git.exe clone --branch dev git://gitorious.org/qt/qt5.git C:\q
git.exe clone --branch dev git://gitorious.org/qt/qtactiveqt.git C:\q\qtactiveqt
git.exe clone --branch dev git://gitorious.org/qt/qtbase.git C:\q\qtbase
git.exe clone --branch dev git://gitorious.org/qt/qtdeclarative.git C:\q\qtdeclarative
git.exe clone --branch dev git://gitorious.org/qt/qtdoc.git C:\q\qtdoc
git.exe clone --branch dev git://gitorious.org/qt/qtgraphicaleffects.git C:\q\qtgraphicaleffects
git.exe clone --branch dev git://gitorious.org/qt/qtimageformats.git C:\q\qtimageformats
git.exe clone --branch dev git://gitorious.org/qt/qtjsbackend.git C:\q\qtjsbackend
git.exe clone --branch dev git://gitorious.org/qt/qtmultimedia.git C:\q\qtmultimedia
git.exe clone --branch dev git://gitorious.org/qt/qtquick1.git C:\q\qtquick1
git.exe clone --branch dev git://gitorious.org/qt/qtscript.git C:\q\qtscript
git.exe clone --branch dev git://gitorious.org/qt/qtsvg.git C:\q\qtsvg
git.exe clone --branch dev git://gitorious.org/qt/qttools.git C:\q\qttools
git.exe clone --branch dev git://gitorious.org/qt/qttranslations.git C:\q\qttranslations
git.exe clone --branch dev git://gitorious.org/qt/qtwebkit.git C:\q\qtwebkit
git.exe clone --branch dev git://gitorious.org/qt/qtwebkit-examples-and-demos.git C:\q\qtwebkit-examples-and-demos
git.exe clone --branch dev git://gitorious.org/qt/qtxmlpatterns.git C:\q\qtxmlpatterns
git.exe clone --branch dev git://gitorious.org/qtplayground/qtdesktopcomponents.git C:\q\qtdesktopcomponents

**Comment by Alexpux** [comment]
I add possibility to build Qt-5.1.0 from tarball. Prebuilded versions you can find at http://sourceforge.net/projects/mingwbuilds/files/external-binary-packages/Qt-Builds/

**Comment by Alexpux** [comment]
I add script to build Qt5 from git from stable branch. You need pass "--qt-version=stable" to build script.
