### ISSUE TITLE
Support 5.0.2 builds

### ISSUE THREAD

**Issue by bratao** [Alexpux/Qt-builds#13]
Hello,
Just a follow up. The 5.0.2 release cycle already started.
Would be nice if this awesome script support this scenario.

The packages are present on: 
http://releases.qt-project.org/digia/5.0.2/

**Comment by Alexpux** [comment]
I add script for Qt-5.0.2 but not test it. If you wish you can test it)

**Comment by bratao** [comment]
Thanks ! It compile nice after you apply this patch :
https://codereview.qt-project.org/#change,47365

**Comment by bratao** [comment]
The lastest version stop working with this script.
I get + C:/QtSDK/Qt-build/work/build-x32/qt-5.0.2/qtbase/configure -prefix c:/QtSDK/Qt32-5.0.2 -opensource -shared -confirm-license -debug-and-release -plugin-sql-ibase -plugin-sql-mysql -plugin-sql-psql -plugin-sql-oci -no-iconv -icu -system-pcre -system-zlib -fontconfig -openssl -no-dbus -angle -platform win32-g++ -nomake tests -nomake examples
Unknown option -prefix c:/QtSDK/Qt32-5.0.2 -opensource -shared -confirm-license -debug-and-release -plugin-sql-ibase -plugin-sql-mysql -plugin-sql-psql -plugin-sql-oci -no-iconv -icu -system-pcre -system-zlib -fontconfig -openssl -no-dbus -angle -platform win32-g++ -nomake tests -nomake examples
Usage: configure [options]

**Comment by Alexpux** [comment]
Maybe removed on of configure options in new Qt

**Comment by Alexpux** [comment]
I fix configuring Qt-5.0.2

**Comment by janickm** [comment]
For the 5.0.1 and 5.0.2 the angle patch fails with

(Stripping trailing CRs from patch.)
patching file qtbase/src/angle/src/config.pri
Hunk #1 FAILED at 13.
1 out of 1 hunk FAILED -- saving rejects to file qtbase/src/angle/src/config.pri.rej

Is this version already tested / should it work?

Patches of 5.0.0 work fine though

**Comment by Alexpux** [comment]
Did you use latest scripts from develop branch? I update master branch to latest develop version. Try update scripts. Qt-5.0.2 do not use this patch anymore.
