### ISSUE TITLE
-O2 -fomit-frame-pointer

### ISSUE THREAD

**Issue by tomilov** [Alexpux/Qt-builds#16]
Line https://github.com/Alexpux/Qt-builds/blob/master/buildall#L303 contains both the "-O2" and the "-fomit-frame-pointer" options, but "http://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html" say, that first one involves the second one. So, it is redundant to add both options.

**Comment by Alexpux** [comment]
Thanks! Fixed.
