### ISSUE TITLE
Qt 5.1.0

### ISSUE THREAD

**Issue by martell** [Alexpux/Qt-builds#19]
Hey Alex

noticed the qt 5.1.0 alpha on sourceforge.

Any chance you guys will be doing a build with the new patch of gcc to 4.7.3 because 4.8.0 is still a bit buggy and unstable?

**Comment by Alexpux** [comment]
Now we can't build Qt-5.1 while not fixed https://bugs.webkit.org/show_bug.cgi?id=114438

**Comment by martell** [comment]
Can you build without webkit for now?

**Comment by Alexpux** [comment]
14.04.2013, â 19:07, martell notifications@github.com íàïèñàë(à):

> Can you build without webkit for now?
> 
> —
> Reply to this email directly or view it on GitHub.

I think yes

**Comment by bratao** [comment]
Its not compiling the GIT because of ANGLE.
Those patches are needed:
http://lists.qt-project.org/pipermail/development/2013-April/010729.html

Also an SSE build is needed

**Comment by martell** [comment]
4.7.3 should have the same stability of 4.7.2 so angle should build.
I done it myself and it works fine in 4.7.3

**Comment by Alexpux** [comment]
bratao: you can apply this patches to your toolchain by hand because I don't yet repack GCC-4.8.0 with this patches

martell: gcc-4.7.3 builds contain last revision of mingw-w64 with patches that bratao need)

**Comment by martell** [comment]
Thanks for clearing that up alex :)
Any way will you guys be providing a 4.7.3 build on sourceforge?

**Comment by Alexpux** [comment]
Yes we have gcc-4.7.3 builds. You can download it from http://sourceforge.net/projects/mingwbuilds/files/host-windows/releases/4.7.3

**Comment by martell** [comment]
Sorry I didn't exactly specify my question.
I'm asking about a QT alpha build with 4.7.3, Will you guys be providing that?

**Comment by Alexpux** [comment]
Hi! I'm now on bussiness trip and have no time to do it. Also I concenrate on get working Qt-5.1 64-bit from git with GCC-4.8.0. If I have some free time I do it

**Comment by martell** [comment]
Thats okay. Thanks for clearing that up Alex
