### ISSUE TITLE
[Bug] --install-top Options. 

### ISSUE THREAD

**Issue by jgh0721** [Alexpux/Qt-builds#2]
--install-top=D:/Qt  ==> unpack, build failed

but

--install-top=/d/Qt ==> unpack, build success

**Comment by Alexpux** [comment]
Try fixed scripts from master branch

**Comment by jgh0721** [comment]
i try below command line :
 ./buildall x32 --install-top=D:/Qt --qt-version=5.0.1 

error message
mingw32 download unpack move -> success
mingw64 download unpack move -> success
preparing done
mkdir: missing operand
Try 'mkdir --help' for more information.
Incorrect directory. 

Is this right situation which you are intend to? 

ps. --install-top=/d/Qt , also doesn't work.

**Comment by Alexpux** [comment]
Fixed in master and develop
