### ISSUE TITLE
Build PCRE 8.33

### ISSUE THREAD

**Issue by AlexandrePTJ** [Alexpux/Qt-builds#26]
At install step, it looks for *.3 man files but has it is shadow build, it crash.
When files are copied from "unpack\pcre-8.33\doc" to "build-x32\pcre-8.33" it works.

Configuration : MSYS2, x32, shared build

**Comment by Alexpux** [comment]
Did you update scripts today?

**Comment by AlexandrePTJ** [comment]
Yes I did

2013/7/12 Алексей notifications@github.com

> Did you update scripts today?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Alexpux/Qt-builds/issues/26#issuecomment-20863463
> .

## 

Cordialement,
Alexandre Petitjean.

**Comment by Alexpux** [comment]
What archive version of msys2 do you use?

**Comment by AlexandrePTJ** [comment]
I am using the last one "x32-msys2-alpha-20130625.tar.xz"*

*
I also have some problem uncompressing openssl, also within a "ln" step.*
*
**

2013/7/12 Алексей notifications@github.com

> What archive version of msys2 do you use?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Alexpux/Qt-builds/issues/26#issuecomment-20863799
> .

## 

Cordialement,
Alexandre Petitjean.

**Comment by Alexpux** [comment]
I see this errors before in MSYS2 but it resolved many times ago.
Try last MSYS2 snapshot http://sourceforge.net/projects/msys2/files/Alpha-versions/32-bit/x32-msys2-alpha-20130709.tar.xz/download. You need completely replace MSYS2 folder and remove all from folder where you build qt.
And see that your scripts are recent.

**Comment by AlexandrePTJ** [comment]
Ok, problem solved, sorry for the annoyance and thanks.

2013/7/12 Алексей notifications@github.com

> I see this errors before in MSYS2 but it resolved many times ago.
> Try last MSYS2 snapshot
> http://sourceforge.net/projects/msys2/files/Alpha-versions/32-bit/x32-msys2-alpha-20130709.tar.xz/download.
> You need completely replace MSYS2 folder and remove all from folder where
> you build qt.
> And see that your scripts are recent.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Alexpux/Qt-builds/issues/26#issuecomment-20864143
> .

## 

Cordialement,
Alexandre Petitjean.
