### ISSUE TITLE
[Request] Build support some opensource 3rd party qt project 

### ISSUE THREAD

**Issue by jgh0721** [Alexpux/Qt-builds#3]
As far as I know,  some Qt 3rd party project( Qt-solutions, Qtilities ... ) needs original Qt source ) to build these projects. 

So I think, If this script support build QtSolutions, Qtilites, QxOrm... and so on, i'm very happy and pleasure! 

Thanks for your efforts.

**Comment by Alexpux** [comment]
These 3rdparty projects not need Qt source only libs, headers and private headers. On Qt4 private headers not installed by default, but they installs with my scripts. For Qt5 private headers are installing by default. If you have any issues with building these projects write me.
