### ISSUE TITLE
Qt Configure error

### ISSUE THREAD

**Issue by ivn** [Alexpux/Qt-builds#34]
Hi! 
While trying to build "./buildall x86_64 --qt-version=5.1.1" I got the following error:

-> qt-5.1.1
---> downloaded
---> unpacked
---> patched
---> Sources already copied
---> configure...Qt configure error

And this is logfile "Qt-builds\work\logs-x86_64\qt-everywhere-opensource-src-5.1.1-.log" contents:

./configure.bat: line 1: @echo: command not found
./configure.bat: line 2: :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: command not found
./configure.bat: line 3: ::: command not found
./configure.bat: line 4: syntax error near unexpected token `('
./configure.bat: line 4:`:: Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).'

Any ideas how to fix this?

**Comment by Alexpux** [comment]
do you use MSYS2 to run scripts?

**Comment by ivn** [comment]
Sorry, didn't noticed in the readme MSYS<b>2</b>. All OK now, thank you.
