### ISSUE TITLE
Build documentations

### ISSUE THREAD

**Issue by bratao** [Alexpux/Qt-builds#5]
Thanks for this awesome script.
One minor issue is the documentations. The option to build the documentations would be avaliable.

**Comment by Alexpux** [comment]
Now I have issues with build documentation. I post bug to developers https://bugreports.qt-project.org/browse/QBS-209

**Comment by bratao** [comment]
I know that this is ultra hackish, but I'm able to generate usable docs by putting this in pkg_install on scenarios qt5.0.1.sh
add:
    cd $BUILD_DIR/$P-$QT_VERSION
    export PATH=$BUILD_DIR/$P-$QT_VERSION/gnuwin32/bin:/c/QtSDK/Qt32-5.0.1/bin:$MINGW_PART_PATH:$WINDOWS_PART_PATH:$MSYS_PART_PATH
    mingw32-make -j8 docs

```
git clone --branch master git://gitorious.org/qtplayground/qtdesktopcomponents.git qtdesktopcomponents
cd qtdesktopcomponents
qmake -r
mingw32-make -j8
mingw32-make -j8 docs
mingw32-make -j8 install
```

**Comment by Alexpux** [comment]
Now documentation for Qt5 generated and installed properly.
