### ISSUE TITLE
Perl is not unpacked

### ISSUE THREAD

**Issue by bratao** [Alexpux/Qt-builds#7]
When building the master or the develop version I get this error :
cp: cannot stat `/c/QtSDK/Qt-builds/src/perl-5.16.2/win32/makefile.mk': No such
file or directory

In fact the folder perl-5.16.2 do not exists. Unpacking the downloaded file solves the problem

**Comment by Alexpux** [comment]
Fixed by https://github.com/Alexpux/Qt-builds/commit/4913c5a9bd62a12e332032e0879c92e25b1c9640 in develop.
