### ISSUE TITLE
Qt5 hangs configuring

### ISSUE THREAD

**Issue by fithisux** [Alexpux/Qt-builds#8]
The title says it all, I am under windows 7 x86 with 
msys+7za+wget+svn+git+mercurial+cvs-rev9

 and configure lasts forever. How can I check what is happening? (debug)

**Comment by Alexpux** [comment]
What version do you configure? Qt4? If yes then on configure press <Enter> button. I can't solve this yet on Qt4. This issue associated with building Oracle SQL Driver. You can found logs in "QT-BUILDS/work/logs-x32|x64|

**Comment by fithisux** [comment]
Unfortunately the problem is on Qt5. How can I give you more feedback?

On Thu, Jan 31, 2013 at 4:42 PM, Алексей notifications@github.com wrote:

> What version do you configure? Qt4? If yes then on configure press button.
> I can't solve this yet on Qt4. This issue associated with building Oracle
> SQL Driver. You can found logs in /work/logs-
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Alexpux/Qt-builds/issues/8#issuecomment-12945255.

## 

Dr. Vasileios Anagnostopoulos (MSc,PhD)
Researcher/Developer
ICCS/NTUA
9 Heroon Polytechneiou Str., Zografou
15773 Athens,Greece
T (+30) 2107723404
M (+30) 6936935388
E vanag@mail.ntua.gr<mailto:vanag@mail.ntua.gr
<axel.spriestersbach@sap.com>>www.ntua.gr
http://www.sap.com/http://www.ntua.gr/ http://www.sap.com/

**Comment by Alexpux** [comment]
Did you install Microsoft DirectX SDK?

**Comment by fithisux** [comment]
No, I have not installed the sdk. My desktop is visual studio free.  I
attach my environment variables (taken from conemu)

On Thu, Jan 31, 2013 at 5:04 PM, Алексей notifications@github.com wrote:

> Did you install Microsoft DirectX SDK?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Alexpux/Qt-builds/issues/8#issuecomment-12946329.

## 

Dr. Vasileios Anagnostopoulos (MSc,PhD)
Researcher/Developer
ICCS/NTUA
9 Heroon Polytechneiou Str., Zografou
15773 Athens,Greece
T (+30) 2107723404
M (+30) 6936935388
E vanag@mail.ntua.gr<mailto:vanag@mail.ntua.gr
<axel.spriestersbach@sap.com>>www.ntua.gr
http://www.sap.com/http://www.ntua.gr/ http://www.sap.com/
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Manolis\AppData\Roaming
CC=gcc
CommonProgramFiles=C:\Program Files\Common Files
COMPUTERNAME=NTUA
ComSpec=C:\Windows\system32\cmd.exe
ConEmuANSI=ON
ConEmuArgs=
ConEmuBackHWND=0x000E053E
ConEmuBaseDir=C:\winoss\ConEmu\ConEmu
ConEmuBuild=121211
ConEmuConfig=
ConEmuDir=C:\winoss\ConEmu
ConEmuDrawHWND=0x000307C6
ConEmuHWND=0x000E07FE
CPLUS_INCLUDE_PATH=C:\langs\Pure\include
C_INCLUDE_PATH=C:\langs\Pure\include
EQ_LIBRARY_PATH=c:\langs\equation\i686-pc-mingw32\lib
FP_NO_HOST_CHECK=NO
G95_LIBRARY_PATH=C:\apps\dragon\g95\lib\gcc-lib\i686-pc-mingw32\4.1.2;C:\apps\dragon\g95\lib
GNUPLOT_LIB=C:\winoss\gnuplot\demo
GOROOT=c:\winoss\go
HAXEPATH=C:\winoss\haxe\Haxe\
HOMEDRIVE=C:
HOMEPATH=\Users\Manolis
JAVA_HOME=C:\langs\jdk7
LIBRARY_PATH=C:\langs\Pure\
LOCALAPPDATA=C:\Users\Manolis\AppData\Local
LOGONSERVER=\NTUA
LUA_DEV=c:\langs\lua
LUA_PATH=;;c:\langs\lua\lua\?.luac
MOZ_PLUGIN_PATH=C:\winoss\SumatraPDF\
NEKO_INSTPATH=C:\winoss\haxe\neko
NEWLISPDIR=C:\langs\newlisp
NUMBER_OF_PROCESSORS=2
OPENMODELICAHOME=C:\winoss\openmodelica\
OPENMODELICALIBRARY=C:\winoss\openmodelica\lib\omlibrary
OS=Windows_NT
OTHER=C:\winoss\haxe\Haxe\;C:\winoss\haxe\neko
Path=C:\winoss\ConEmu\ConEmu;C:\Windows\system;C:\Windows\System32;C:\Windows\System32\Wbem;C:\langs\jdk7\bin;c:\winoss\go\bin;C:\winoss\texlive\bin\win32
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.tcl;.wlua;.lexe;.RB;.RBW
PHPRC=C:\winoss\PHP\
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_IDENTIFIER=x86 Family 6 Model 23 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=170a
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
PURELIB=C:\langs\Pure\lib
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\Manolis\AppData\Local\Temp
TERM=dumb
TMP=C:\Users\Manolis\AppData\Local\Temp
USERDOMAIN=NTUA
USERNAME=Manolis
USERPROFILE=C:\Users\Manolis
windir=C:\Windows
windows_tracing_flags=3
windows_tracing_logfile=C:\BVTBin\Tests\installpackage\csilogfile.log

**Comment by Alexpux** [comment]
You can't build Qt5 without DirectX SDK. You can download it from http://www.microsoft.com/en-us/download/details.aspx?id=6812
